version: 2
jobs:
  py3test:
    working_directory: ~/pymatgen-diffusion
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
        environment:
          PMG_MAPI_ENDPOINT: https://zola.lbl.gov/rest/v2
    # parallelism: 4
    steps:
      - checkout
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            if [ ! -d "/root/miniconda3/envs/test_env" ]; then conda create --quiet --yes --name test_env python=3.6; fi
            source activate test_env
            conda install --quiet --yes numpy scipy matplotlib sympy cython
            # conda update --quiet --all
            mkdir coverage_reports
            pip install --upgrade pip
            pip install --upgrade numpy
            pip install --quiet --ignore-installed -r requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/root/miniconda3/envs/test_env"
      - run:
          command: |
            # Add executables and path.
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            source activate test_env
            pip install --quiet -e .
            nosetests --config=nose.cfg --cover-html --cover-html-dir=coverage_reports --with-timer --timer-top-n 30
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
