version: 2
jobs:
  py3test:
    working_directory: ~/pymatgen-diffusion
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
        environment:
          PMG_MAPI_ENDPOINT: https://zola.lbl.gov/rest/v2
    # parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            if [ ! -d "/root/miniconda3/envs/test_env" ]; then conda create --quiet --yes --name test_env python=3.7; fi
            source activate test_env
            conda uninstall numpy scipy
            mkdir coverage_reports
            pip install --upgrade pip
            pip install --force-reinstall numpy
            pip install --force-reinstall scipy
            pip install --force-reinstall cython
            pip install --quiet -r requirements.txt -r requirements-ci.txt
      - run:
          command: |
            # Add executables and path.
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            source activate test_env
            pip install --quiet -e .
            nosetests --config=nose.cfg --cover-html --cover-html-dir=coverage_reports --with-timer --timer-top-n 30
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
